version: '{build}-{branch}'

os: 'Visual Studio 2015'

environment:
  matrix:
    - ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      GOPATH: c:\gopath
      GOARCH: amd64
      CGO_ENABLED: 1
    - ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      GOPATH: c:\gopath
      GOARCH: 386
      CGO_ENABLED: 1

branches:
  only:
    - master

clone_folder: C:\gopath\src\github.com\square\ghostunnel

before_build:
  # Go paths
  - set PATH=C:\go19\bin;C:\%GOPATH%\bin;%PATH%
  # MSYS paths
  - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%
  # Install build deps
  - bash -lc "for n in `seq 1 3`; do pacman --noconfirm -Syyuu && break || sleep 15; done"
  - bash -lc "for n in `seq 1 3`; do pacman --noconfirm -S mingw-w64-%MSYS2_ARCH%-libtool && break || sleep 15; done"

build_script:
  - go build -o ghostunnel.exe -i .
  - go test -v .
