---

language: go

sudo: required
dist: trusty

services:
  - docker

go:
  - 1.8
  - 1.9

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - go get github.com/mattn/goveralls

install:
  # Ensure we can build with/without CGO
  - CGO_ENABLED=0 go build .
  - CGO_ENABLED=1 go build .
  # Build docker images
  - make docker-build
  - GO_VERSION=${TRAVIS_GO_VERSION}-stretch make docker-test-build

script:
  - make docker-test-run

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage-merged.out -service=travis-ci
