language: go

sudo: false

env:
  - GO15VENDOREXPERIMENT=1

go:
  - 1.5
  - 1.6

before_script:
  - go vet .

before_install:
  - python --version
  - openssl version
  - go get github.com/Masterminds/glide
  - make depends

install:
  - make build 

script:
  - make test
