language: go

sudo: required
dist: trusty

env:
  - GO15VENDOREXPERIMENT=1

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

go:
  - 1.5
  - 1.6
  - tip

before_script:
  - go vet .

before_install:
  - python --version
  - openssl version
  - go get github.com/Masterminds/glide
  - make depends

install:
  - make build 

script:
  - make test
