language: go

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

go:
  - 1.5
  - tip

before_install:
  - python --version
  - openssl version

install:
  - make build 

script:
  - make test
