language: go

sudo: false

matrix:
  fast_finish: true

go:
  - 1.3
  - 1.4
  - 1.5

before_install:
  - python --version
  - openssl version

install:
  - go get -v ./...
  - go build -v

script:
  - go get github.com/stretchr/testify/assert
  - make test
