language: go

sudo: required
dist: trusty

services:
  - docker

env:
  - GO15VENDOREXPERIMENT=1

go:
  - 1.6

before_install:
  - sudo `which pip3` install pyopenssl
  - go get github.com/Masterminds/glide
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - make depends

install:
  - make build 
  - docker build -t square/ghostunnel .
  - docker build -t redis-tls docker/redis-tls

before_script:
  - go vet .

script:
  - make test

after_success:
  - gocov convert *.out */*.out > gocov.json
  - $HOME/gopath/bin/goveralls -gocovdata gocov.json -service=travis-ci

