language: go

sudo: required
dist: trusty

services:
  - docker

env:
  - GO15VENDOREXPERIMENT=1

go:
  - 1.6

before_install:
  - sudo `which pip3` install pyopenssl
  - go get github.com/Masterminds/glide
  - make depends

install:
  - make build 
  - docker build -t square/ghostunnel .
  - docker build -t redis-tls docker/redis-tls

before_script:
  - go vet .

script:
  - make test
